### PR TITLE
solved bug #102 issue

### LINKED ISSUE #102: 🐛: ## 🐞 Bug: Input Fields Lose Focus After Each Keypress
### Description
When typing in the **Get in Touch** form, the input fields do not allow continuous typing. The user has to click the input field after every letter to continue typing. This behavior occurs in all form fields, including Name, Email, Phone, Subject, and Message.

### 🧪 Steps to Reproduce
1. Go to the "Get in Touch" section of the website.
2. Click on any input field (e.g., Name).
3. Start typing more than one character.
4. Notice that only one letter gets typed, and the cursor focus is lost after each keystroke.

### 🔁 Expected Behavior
- User should be able to type continuously in input fields without having to re-click the field each time.

### 🧩 Possible Causes
- `onChange` handler not properly updating state.
- Input value being reset on every render.
- Uncontrolled vs. controlled component mismatch.
- Auto-focus or DOM manipulation re-triggering focus.
- Component re-render loop.

### 💡 Suggested Fix
Ensure the input fields are implemented as **controlled components** with correct `value` and `onChange` bindings. Avoid resetting the input state on each render.

#### Example (React):
```jsx
const [formData, setFormData] = useState({ name: "", email: "", phone: "", subject: "", message: "" });

const handleChange = (e) => {
  setFormData({ ...formData, [e.target.name]: e.target.value });
};

<input
  type="text"
  name="name"
  value={formData.name}
  onChange={handleChange}
/>
```

### 📷 Screenshot
Bug Screenshot

### 📎 Additional Context
- This bug affects user experience and form usability.
- Occurs on all major browsers.

Image
Assign this to me under SSOC .Please mark it as intermediate level .
@UTSAVS26 

### ✅ Fix Approach

1. **Ensure Controlled Components:**
   - All input fields (e.g., `<input>`, `<textarea>`) should use `value` and `onChange` properly.
   - The input’s `value` should be tied to state, and `onChange` should update that state.

2. **Avoid Re-rendering Issues:**
   - Make sure no logic in your component (e.g., props, effects, or reassignments) resets the input state or refocuses fields on every render.
   - Avoid assigning new inline object values inside `value={}` or `onChange={}` props.

3. **Check AutoFocus and Ref Usage:**
   - If you’re using `autoFocus` or manually focusing elements using `ref`, ensure this doesn’t run on every re-render.

4. **Fix Sample (React):**
   ```jsx
   const [formData, setFormData] = useState({
     name: "",
     email: "",
     phone: "",
     subject: "",
     message: ""
   });

   const handleChange = (e) => {
     const { name, value } = e.target;
     setFormData((prev) => ({ ...prev, [name]: value }));
   };

   <input
     type="text"
     name="name"
     value={formData.name}
     onChange={handleChange}
     placeholder="Enter your name"
   />
   ```

5. **Use `useCallback` if Needed:**
   - If `handleChange` or other handlers are causing re-renders, memoize them with `useCallback`.

6. **Check Conditional Rendering:**
   - Don’t conditionally render inputs inside `map` or ternary expressions unless necessary. It may reset the DOM node and its internal state (cursor position) every render.

### 🧼 Clean Code Tip:
Group form state together and avoid recreating input handlers on each render.

### 📷 Screenshots (Optional)

_No response_

### 👤 Full Name

Disha Agrawal

### 🎓 Participant Role

SSOC

### PR DESCRIPTION
**Pull request by dishaagrawalcodes**
# 🚀 Pull Request for CLUSTER Portal

### Related Issue Title  
🐞 Bug: Input Fields Lose Focus After Each Keypress

---

### Project Goal  
Fix the bug where input fields in the "Get in Touch" form lose focus after each keystroke, preventing users from typing continuously. The goal is to ensure a smooth and functional user experience when filling the contact form.

---

### Your Full Name  
Disha Agrawal

---

### GitHub Username  
@dishaagrawalcodes

---

### Email Address  
dishaagrawal9568@gmail.com

---

### Your Role  
SSOC (Social Summer of Code) Contributor

---

### Issue Number (if any)  
Closes #102 

---

### Describe Your Changes  
- Moved `InputField` component outside `ContactPage` to prevent redefinition on every render.
- Made each form input a fully controlled component using `value` and `onChange`.
- Fixed the phone field's validation logic to properly update the state without breaking focus.
- Passed `error` messages explicitly for each field to support inline validation.
- Ensured smooth typing experience across all form fields.

---

### Type of Change  
✅ Bug fix (non-breaking change)  
⬜ New feature (non-breaking change)  
⬜ Code style / formatting  
⬜ Breaking change (may cause backward incompatibility)  
⬜ Documentation update  

---

### Testing Details  
- Tested on Chrome, Firefox, and Edge.  
- Manually verified all fields retain focus and allow smooth typing.  
- Verified error messages and validations render correctly.  
- Ensured form submission works without breaking layout or data.

---

### Checklist  
✅ I have followed the project's contributing guidelines.  
✅ I have self-reviewed my code.  
✅ I have added comments where necessary.  
⬜ I have updated documentation if needed.  
✅ My changes do not generate new warnings.  
⬜ I have added tests or screenshots proving my fix/feature works.  
⬜ All dependent changes have been merged.
---
### Screenshot

image
@UTSAVS26

### CODE REVIEW

File: src/components/contact/ContactPage.jsx [hunk 1]
```diff
@@ -4,6 +4,31 @@ import AnimatedBackground from '../common/AnimatedBackground';
 import GlassCard from '../common/GlassCard';
 import { FiMail, FiUser, FiPhone, FiEdit, FiSend } from 'react-icons/fi';
 
+// ✅ 1. InputField moved OUTSIDE ContactPage to avoid re-creation on each render
```
Comment (UTSAVS26) [inline src/components/contact/ContactPage.jsx:7]: Can you please remove the comment from here

Comment (dishaagrawalcodes) [reply src/components/contact/ContactPage.jsx:7]: > Can you please remove the comment from here

Yes

**Comment by dishaagrawalcodes** [comment]
done @UTSAVS26
